name: Go
on:
  - push
  - pull_request
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      GOPATH: ${{ HOME }}/.cache
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ${{ HOME }}/.cache
          key: ${{ runner.os }}-${{ hashFiles('**/go.sum') }}
      - name: Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Test
        run: |
          CGO_ENABLED=0 GO111MODULE=on go test -cover -covermode=atomic -coverprofile=coverage.txt -v ./...
      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
